# Generated by Django 4.0.5 on 2022-07-27 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK'), ('yellow', 'YELLOW'), ('purple', 'PURPLE'), ('light green', 'LIGHT GREEN'), ('light blue', 'LIGHT BLUE'), ('pink', 'PINK'), ('light orange', 'LIGHT ORANGE'), ('gray', 'GRAY'), ('light yellow', 'LIGHT YELLOW'), ('light purple', 'LIGHT PURPLE'), ('white', 'WHITE'), ('rainbow', 'RAINBOW')], default='green', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('mylar', 'MYLAR'), ('latex', 'LATEX')], default='latex', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('standard', 'STANDARD'), ('large', 'LARGE'), ('x-large', 'X-LARGE')], default='small', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=120, null=True)),
                ('vendor_quantity', models.PositiveIntegerField(null=True)),
                ('vendor_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
