# Generated by Django 4.0.6 on 2022-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_description_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120, null=True)),
                ('source_email', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
